### ISSUE TITLE
jasny-bootstrap.js для меню-слайдера

### ISSUE THREAD

**Issue by pelid** [pelid/mm-icebox#45]
Уперлось в архитектуру - меню должно находиться снаружи pageMountPoint. Нужен еще один mixin взамен <navbar4page>

Также стоит протюнить анимацию:
```css
  .canvas-sliding {
      -webkit-transition: right .15s ease-out, left .15s ease-out;
      transition: right .15s ease-out, left .15s ease-out;
  }
```
